### ISSUE TITLE
Add option to change enrollment type to manual on merging users' enrollments (in order to handle external database enrollments)

### ISSUE THREAD

**Issue by evandonovan** [ndunand/moodle-tool_mergeusers#105]
I am running Master of the Merge Users tool, downloaded today 9/1/15, on Moodle 2.9.1+ (Build: 20150813).

I am attempting to merge two users, both of whom had courses in which they were enrolled via the External database method.

The initial update queries for the users work properly. However, because Moodle uses the external database as canonical for enrollments when this method is used, when the "user to keep" actually logs in, the enrollment that had been added by the merge process is lost. Likewise, when the "user to remove" logs in, (if not suspended) they are added back in to the course that had been given to the "user to keep".

I propose that there be a option in the plugin config screen to handle this case. If set, the plugin would automatically change all external database enrollments to manual enrollments as part of the merge process. The option could be a checkbox called "Change external database enrollments to manual enrollments" or something similar.

I believe that this, if added, would resolve any issues around merging when external database enrollments have been added to either user.

In the interim, does anyone know what the query would be that I would manually run to fix this prior to the user's logging in and inadvertently reverting my merge?

Thanks, Evan Donovan
Director of Educational Technology
City Vision University

**Comment by evandonovan** [comment]
I figured out the SQL queries necessary to do this process manually:

1) Get the id's of the users from the merge users log.

2) Select the users' enrollments to get the enrolid's.

`select * from mdl_user_enrolments where userid in (2090, 2091);`

3) Use the enrolid's to update the relevant records in the mdl_enrol table.

`update mdl_enrol set enrol = replace(enrol,'database','manual') where id in (1146,1147);`

Note that this will only work if done immediately after the merge process, because otherwise the users might have a change to log in again and add new records from the external database.

I added these queries a) in case anyone else needs them, b) as a reference to myself, and c) in case they are a help to anyone who wishes to add this feature to the (very-useful) plugin. I unfortunately don't know enough about the plugin to add this myself.

**Comment by jpahullo** [comment]
Hi Evan!

Thanks for reporting this subject, it is always interesting hearing about its use and problems and successes found around this plugin.

Having taken a look at the whole issue, let me say the following, in my honest opinion:

**I would tackle the problem from the source.**

The real problem is that your external database does not reflect the change on person's username. Therefore, in a normal operation of Moodle, when users log in again update users' enrollments. And this is ok. Once external database reflect the correct usernames, then you should be able to merge users and all things would be correct, both in Moodle and in the external database.

Following your suggestion, adding this option to the setting makes me think about it like a patch for a specific case, but not for a normal, general operation.

I repeat, it's my honest opinion.

Regarding the SQL, if you have the specific ids, you needed just a `set enrol='manual'` as part of your SQL. This patch seems a correct workaround for your problem. But let me say another thing: what if that enrolment is suspended from external database? How would you track that all enrollments from external database remain correct if we are updating its type to manual?

I would need more thoughts about it and brainstorming to decide if we add this option to the plugin. @ndunand ?

Thank you. Thank you so much to report any possibility to improve this plugin.

Regards,

Jordi

**Comment by jpahullo** [comment]
Let me say another example.

In our institution, we have problems on people changing their usernames. But all these people have their usernames updated in the LDAP and other sources we have. So that, after that username change is performed in all sources, we can successfully and accordingly merge both users.

Regards,

Jordi

**Comment by evandonovan** [comment]
Thanks, Jordi. I understand your position, and would prefer to do it in the external database if that were possible.

Unfortunately, the external database enrollments are created from a SQL view that joins various tables in a Drupal database, and there is no equivalent user merge tool in Drupal. Therefore, it is much easier to do the merges on the Moodle side. We really just use the external database to populate Moodle in the first place. In our case, we wouldn't do suspensions in the external database once the users' enrollments had been changed to manual; we could just do them in Moodle itself.

**Comment by jpahullo** [comment]
Hi Evan!

Thanks for your words. 

I think the solution you proposed does not tackle all cases from enrollments and unenrollments from externat database into Moodle. 

Maybe in your institution, a person being enrolled into a course will never unenrol. However, in general, it may happen. If you are moving the enrollment to manual, how the external database would unenrol whenever necessary? If it remains as manual, the user could have access into Moodle when the user shouldn't.

If you have cooked the SQL view, you also could rename usernames from the SELECT statement defined int the VIEW, so that you "actually" are merging any users in the Drupal site (without affecting to it, in fact, just to the data it provides outside). After that, you could user this merge user tool normally.

Keep talking about it.

Jordi

**Comment by ndunand** [comment]
Hi all,

Thanks for reporting this, and also for providing a lead towards a possible solution.

My first opinion would be to agree with Jordi, as this is a very specific case, and – as Jordi stated – one would normally expect the third-party system (in your case, Drupal) to reflect the correct state of the usernames.

I also think Jordi's last post actually provides a more robust solution to your problem.

**Comment by evandonovan** [comment]
Thanks Jordi & Nicolas,

I hadn't thought about modifying the view. I suppose I could create a normalization table to which it would join, and that table would match old users to new users.

However, if I did that, what about the other data that needs to be merged (grades & activities)? I think I would still need to merge that in Moodle using the user merge plugin, because otherwise it would still be linked to the old & now defunct user.

**Comment by jpahullo** [comment]
Thanks to all!

Evan, there are lots of possibilities in updating the view (including modifying the Drupal database schema to reflect changes in usernames, as you proposed). A naive solution for very few user changes, would be to use a "REPLACE" function over the Drupal's username column. But it would not scale as much as your proposal.

Regarding to the use of the merge users tool, of course, after tackling this change of usernames in Drupal's side, you can use this plugin to reflect the correct Moodle status. Right after, user login will no longer revert Moodle records as it happened before to you.

Hoping this helps,

Jordi
