### ISSUE TITLE
No completed  activity under Course > Reports > Activity completion after merging

### ISSUE THREAD

**Issue by matheus-crivellari** [ndunand/moodle-tool_mergeusers#129]
I merged two users together (one manually registered and another registered from LDAP). Both had different activities completed on a same given course. 

Now, when I access the **Course > Reports > Activity completion** report the resulting merged user doesn't have any completed activity on this course. Also, if I use the **"Log in as"** feature and I go to the course as this specific user, all of its activities appears as if they were not completed.

Do you have any clues if this is a bug, or any kind of your plugin limitation? Sorry if this was a closed issue already, I couldn't find it on the issue tracker.

Thanks in advance.

**Comment by jpahullo** [comment]
Hi!

Thank you so much for your feedback.

As far as I know, this is the first time we know about this issue. It seems like there is a need to update the completion status of the activities after merging users.

Would you mind to report here which are the database tables and/or Moodle processes involved on setting/updating the completion status? This would be a great point to start from.

Thank you so much.

Jordi

**Comment by matheus-crivellari** [comment]
We've made some test around some specific users, comparing their completion statuses before and after the merge. We've used this plugin to merge manually registered user to an LDAP registered user.

We found an specific course (common for these two users) where user A (manual) had more completed activities than user B (ldap), we then chose  to merge everything from user A to B and then, the resulting user (ldap) had less completed activities than it had previously.

Looking further at the database, we ran this query:

```
SELECT
 *
FROM
   mdl_course_modules_completion c
INNER JOIN mdl_course_modules m ON c.coursemoduleid = m.id
WHERE
   c.userid = ?
AND m.course = ?
AND m. COMPLETION > 0
AND c.completionstate = 1
```

and we noticed that the plugin had deleted user A's entries and kept user B's entries even user B's being less important (incomplete statuses) than A's. Table: **mdl_course_modules_completion** .

Thanks in advance.

Matheus

**Comment by jpahullo** [comment]
Thanks you so much!!

What you stated in your last paragraph is strange for us: this plugin actually "moves" all information from user A to user B. In special cases we also deal with duplicated entries and so forth.

A special case is related to the table course_modules_completion, which has a compound index (see config/config.php). In that case, this plugin leaves the entries related to user B and those from user A that do not match with coursemodules already existing in user B. In addition, this plugin removes the entries from user A matching the coursemodule with user B.

Summing up, I think what remains in that table from the merging users operation is the completion status from user B plus all records not matching on coursemodule from user A.

What you talk about "importance" is not true. Merge users considers registries from both users and remains that details from user B and adding that from user A (not matching any existing registries from user B).

Moreover, think that this plugin proceed this way thrughout the whole database, leaving the system "consistent".

For a moment, imagine you reach to leave all completion statuses from both users A and B into user B (somehow as a logical OR) with the current plugin implementation. Then, with the normal behaviour of this plugin, you will be able to see "completed" activities with no user delivery (since user B has not completed that particular activity).

It is important to leave user data "consistent" and this is the core goal of this plugin (let me say, it's not easy).

So, by now, I think the current implementation is correct and "consistent" (even though some not detected case to date may arise).

What you talk about is more like a rethinking of the plugin's behavior, if I'm not wrong, that instead of proceeding as I told above, your proposal should be to let the plugin proceed merging users as with a logical OR (adding semantics to every single activity, whatever, into Moodle). And this is even more complex than the current plugin's design: you should consider the relation between tables for the same user and item (activity, whatever) within the database. In my opinion, this is not affordable, except from the proper Moodle code.

I proposed to Moodle HQ to define an API to merge users information correspondingly, so that the Moodle core and any kind of plugin could implement that API with full knowledge of how to proceed.

Therefore, I think we cannot afford this in the way you expect. Sorry.

Jordi

**Comment by matheus-crivellari** [comment]
Thank you very much for the explanation!

We've been making more tests and we checked the behaviour you mentioned is working as expected indeed.

Prioritizing data consistance, it makes total sense to move only A's entries when they don't match any of B's entries. We figured out that the "incomplete statuses" belonged to B so it kept B's completion not A's. In some cases, user B hadn't even attempted an activity and A's had completed, so after the merge, B had a new entry where it had completed that specific activity. 

This was what caused us to think it was a bug.

Thank you very much.

Matheus

**Comment by luisdev** [comment]
> I proposed to Moodle HQ to define an API to merge users information correspondingly

Jordi, did you make that proposal via the [Moodle Tracker](https://tracker.moodle.org/)? If so, what is the tracker id so we can vote for it?

**Comment by jpahullo** [comment]
Thanks for your words.

My University is one of the Moodle User Association, where every semester they can propose some subject to be done in Moodle. This is the second semester we propose this plugin to be in core. So, there is no public Moodle Tracker yet. Moreover, I think things would be easier if Moodle had a Merging API which will maintain all data consistent, even in very particular cases, like quiz attempts and so many other items.
