### ISSUE TITLE
Not all logs merged

### ISSUE THREAD

**Issue by BakaKiller** [ndunand/moodle-tool_mergeusers#147]
Hi,
When merging infos from logstore_standard_log, data related to old user through relateduserid is not merged, which can cause problems with logging enrolments (and probably other stuff)...
Could you check this when you have time ? Thanks !

**Comment by jpahullo** [comment]
Ups! Thanks a lot for giving us feedback. We will consider that field in future releases. Thanks a lot!

As always, if you can build a patch for this issue, just build a PR and it will be quicker.

Thanks a lot!

Jordi

**Comment by BakaKiller** [comment]
I'll try to find some time to do so but can't be sure I'll be able to !

Good luck for everything anyways ^^

**Comment by jpahullo** [comment]
If you want to bypass this limitation by now, you can add a local file: `config/config.local.php` with the following content: (if it does not exist, or append otherwise)

```
<?php
defined("MOODLE_INTERNAL") || die();
return array(
    'userfieldnames' => array(
        'logstore_standard_log' => array('userid', 'relateduserid'),
    ),
);
```

This config will be merged and appended to the default one (in the `config/config.php`) and it should work.

IMPORTANT: Try it in a testing environment before putting it in production.

Please, give us feedback if it works ok.

Thank you so much,

Jordi

**Comment by BakaKiller** [comment]
Sorry for the delay, I couldn't test your workaround as I had already corrected the merge with a SQL query (something like UPDATE *_logstore_standard_log SET relateduserid = {{newuserid}} WHERE relateduserid = {{olduserid}} )

**Comment by jpahullo** [comment]
It doesn't matter. However, if you lieve this config file into your plugin, you will **prevent** new issues like this.

**Comment by BakaKiller** [comment]
Yup, we shouldn't have a lot of cases like this but if we have another, I'll sure try and let you know !

Thanks again !

**Comment by jpahullo** [comment]
adding it to repository.

**Comment by jpahullo** [comment]
related PR #159

**Comment by jpahullo** [comment]
done
