### ISSUE TITLE
tool_mergeusers index page takes ~15 minutes to load on a large database.

### ISSUE THREAD

**Issue by sayoder** [ndunand/moodle-tool_mergeusers#176]
Hi there,

When the tool_mergeusers index page loads, the`getCurrentUserFieldNames` function in lib/mergeusertool.php is called once for every table in the Moodle database. That function runs a very expensive SELECT from the `INFORMATION_SCHEMA.Columns` table which can take 1-2 seconds on a large database. On our Moodle database, there are around 700 tables, so the index page takes about 15 minutes to load.

Is there any way to write this code that doesn't involve querying against `INFORMATION_SCHEMA.Columns`?

**Comment by jpahullo** [comment]
Hi!

Thanks for the feedback.

Good point! It'll be a very good point for performance improvement.

Instead of using raw SQL, we could use the db manager from Moodle core, that uses cache, and sould improve a lot its performance.

Do you think you could build a patch for that and contribute it as a PR?

Thansk for your time.

**Comment by sayoder** [comment]
Hi there,

Sorry I was never able to contribute a patch for this -- it looks like it's been addressed in the most recent version, so I'll close this down.

Thanks!

**Comment by jpahullo** [comment]
Thanks!!!
